apiVersion: v1
kind: ServiceAccount
metadata:
  name: functions-api
  namespace: functions-system
imagePullSecrets:
  - name: harbor-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: function-runtime
  namespace: functions
automountServiceAccountToken: false
imagePullSecrets:
  - name: harbor-secret
